---
title: Professional Ruby on Rails development & consulting | CodeGyver
email: contact@codegyver.com
description: >
  CodeGyver is professional Ruby on Rails (RoR) development and
  consulting company based in Poland. We built internet startups and
  with excellent Ruby on Rails framework and newest technologies
  (HTML5, CSS3, Javascript).  Write an awesome description for your new site here.
keywords: ruby on rails development, ruby on rails consulting, ruby, rails, ror, web development, company
baseurl: ''
url: http://codegyver.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      path: ''
    values:
      layout: default
  - scope:
      type: projects
    values:
      layout: project
      nav: projects
include: [_pages]
sass:
  sass_dir: css/vendor
  style: compressed
collections:
  projects:
    output: true
