---
# Setup
baseurl: ''
excerpt_separator: <!--more-->
markdown: redcarpet
highlighter: pygments
permalink: pretty
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - tmp
sass:
  sass_dir: css/vendor
  style: compressed
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Data
title: Codegyver
description: Blog
url: https://codegyver.com
author:
  name: Zbigniew Pieślak
  url: https://codegyver.com
paginate: 5
