---
# Setup
baseurl: /
markdown: redcarpet
highlighter: pygments
permalink: pretty
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
sass:
  sass_dir: css/vendor
  style: compressed

# Data
title: Codegyver
tagline: Personal blog
description: Personal blog
url: http://hyde.getpoole.com
author:
  name: Zbigniew Pieślak
  url: http://codegyver.com

paginate: 5

# Custom vars
version: 2.1.0
